src/Entity/Event.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\EventRepository")
 */
class Event
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $type;

    /**
     * @ORM\Column(type="date")
     */
    private $date_start;

    /**
     * @ORM\Column(type="date")
     */
    private $date_end;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $lieu;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $ville;

    /**
     * @ORM\Column(type="text")
     */
    private $description;

    /**
     * @ORM\Column(type="float")
     */
    private $prix;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Artiste", inversedBy="events")
     */
    private $artiste_id;
    
    /**
     * @Assert\Image(
     *     minWidth = 200,
     *     maxWidth = 400,
     *     minHeight = 200,
     *     maxHeight = 400
     * )
     */
    protected $image;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getType(): ?string
    {
        return $this->type;
    }

    public function setType(string $type): self
    {
        $this->type = $type;

        return $this;
    }

    public function getDateStart(): ?\DateTimeInterface
    {
        return $this->date_start;
    }

    public function setDateStart(\DateTimeInterface $date_start): self
    {
        $this->date_start = $date_start;

        return $this;
    }

    public function getDateEnd(): ?\DateTimeInterface
    {
        return $this->date_end;
    }

    public function setDateEnd(\DateTimeInterface $date_end): self
    {
        $this->date_end = $date_end;

        return $this;
    }

    public function getLieu(): ?string
    {
        return $this->lieu;
    }

    public function setLieu(string $lieu): self
    {
        $this->lieu = $lieu;

        return $this;
    }

    public function getVille(): ?string
    {
        return $this->ville;
    }

    public function setVille(string $ville): self
    {
        $this->ville = $ville;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getPrix(): ?float
    {
        return $this->prix;
    }

    public function setPrix(float $prix): self
    {
        $this->prix = $prix;

        return $this;
    }

    public function getArtisteId(): ?Artiste
    {
        return $this->artiste_id;
    }

    public function setArtisteId(?Artiste $artiste_id): self
    {
        $this->artiste_id = $artiste_id;

        return $this;
    }
    public function setImage(File $file = null)
    {
        $this->headshot = $file;
    }

    public function getImage()
    {
        return $this->headshot;
    }
}

src/Form/EventType.php
<?php

namespace App\Form;

use App\Entity\Event;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class EventType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('type')
            ->add('date_start')
            ->add('date_end')
            ->add('lieu')
            ->add('ville')
            ->add('description')
            ->add('prix')
            ->add('artiste_id')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Event::class,
        ]);
    }
}

src/Controller/EventController.php
<?php

namespace App\Controller;

use App\Entity\Event;
use App\Form\EventType;
use App\Entity\User;
use App\Repository\EventRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Translation\TranslatorInterface;

/**
 * @Route("/event")
 */
class EventController extends AbstractController
{
    /**
     * @Route("/", name="event_index", methods={"GET"})
     */
    public function index(EventRepository $eventRepository, TranslatorInterface $translator): Response
    {   
        if ($this->isGranted('IS_AUTHENTICATED_FULLY')) {
       
        $cityUser=$this->getUser()->getVille();
       
        $cities = $this->getDoctrine()
                         ->getManager()
                         ->getRepository(Event::class)
                         ->requestCity($cityUser);
        $NbCities = $this->getDoctrine()
                         ->getManager()
                         ->getRepository(Event::class)
                         ->getNbEventinCity($cityUser);
        
        $messageEvents = $translator->trans('num_of_event', ['NbCities' => $NbCities]);
        return $this->render('event/index.html.twig', [
            'events' => $eventRepository->findAll(), 
            'city'=> $cities,
            'NbCities'=>$NbCities,
            'messageEvents' => $messageEvents
        ]);
        }
        return $this->render('event/index.html.twig', [
            'events' => $eventRepository->findAll(), 
           // 'city'=> $cities,
            // 'NbCities'=>$NbCities,
            // 'messageEvents' => $messageEvents
        ]);

    }

    /**
     * @Route("/new", name="event_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $event = new Event();
        $form = $this->createForm(EventType::class, $event);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($event);
            $entityManager->flush();

            return $this->redirectToRoute('event_index');
        }

        return $this->render('event/new.html.twig', [
            'event' => $event,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="event_show", methods={"GET"})
     */
    public function show(Event $event, \App\Local\Localisation $h): Response
    {
      
        return $this->render('event/show.html.twig', [
            'event' => $event,
            'ville'=> $h->oneCity($event->getVille()),
        ]);
    }

    /**
     * @Route("/{id}/edit", name="event_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Event $event): Response
    {
        $form = $this->createForm(EventType::class, $event);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('event_index');
        }

        return $this->render('event/edit.html.twig', [
            'event' => $event,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="event_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Event $event): Response
    {
        if ($this->isCsrfTokenValid('delete'.$event->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($event);
            $entityManager->flush();
        }

        return $this->redirectToRoute('event_index');
    }

    
}

templates/event/_delete_form.html.twig
<form method="post" action="{{ path('event_delete', {'id': event.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ event.id) }}">
    <button class="btn">Delete</button>
</form>

templates/event/_form.html.twig
{{ form_start(form) }}
<div class="my-custom-class-for-errors">
    {{ form_errors(form) }}
</div>

<div class="row">
    <div class="form-group col-md-5">
        {{ form_row(form.artiste_id) }}
    </div>
    <div class="form-group col-md-10">
        {{ form_row(form.type) }}
    </div>
    <div class="form-group col-md-6">
        {{ form_row(form.date_start) }}
    </div>
    <div class="form-group col-md-6">
        {{ form_row(form.date_end) }}
    </div>
    <div class="form-group col-md-5">
        {{ form_row(form.lieu) }}
    </div>
    <div class="form-group col-md-5">
        {{ form_row(form.ville) }}
    </div>
    <div class="form-group col-md-10">
        {{ form_row(form.description) }}
    </div>
    <div class="form-group col-md-5">
        {{ form_row(form.prix) }}
    </div>

</div>
<div class="button">
    <button class="btn btn-primary">{{ button_label|default('Save') }}</button></div>

{{ form_end(form) }}

templates/event/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Event{% endblock %}

{% block body %}
    <h1>Edit Event</h1>

    {{ include('event/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('event_index') }}">back to list</a>

    {{ include('event/_delete_form.html.twig') }}
{% endblock %}

templates/event/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Event{% endblock %}

{% block body %}
    <h2>{% trans %}Evenement{% endtrans %}</h2>
    <h3>{% trans %}Les prochains concerts dans ma ville{% endtrans %}</h3>
    {% if is_granted('IS_AUTHENTICATED_FULLY') %} 
<p>{% trans with {events: NbCities } %} num_of_event {% endtrans %}</p>
<ul>
{% for citi in city %}
<li><a href="{{ path('event_show', {'id': citi.id})}}"><strong> {{ citi.artisteId.nom }}</strong></a></li>
<li>{{ citi.dateStart ? citi.dateStart|date('d-m-Y') : '' }}

<li>{{ citi.lieu }}</li>
<li>{{ citi.ville }}</li>
{% endfor %}
{% else %}
<p>Connectez-vous pour voir les événements dans votre ville.
{% endif %}
<ul>
    {{ asset ('./image/concertP.jpg') | figure('That\'s my show', '1200px','600px','slam dans le public') | raw }}


<h3>{% trans %}Tous les concerts{% endtrans %}</h3>
    <table class="table table-bordered table-hover p-3 m-4">
        <thead class="thead-dark">
            <tr>
                <th>{% trans %}Artiste{% endtrans %}</th>
                <th>{% trans %}Type{% endtrans %}</th>
                <th>{% trans %}Date{% endtrans %}</th>
                
                <th>{% trans %}Lieu{% endtrans %}</th>
                <th>{% trans %}Ville{% endtrans %}</th>
                
                <th>{% trans %}actions{% endtrans %}</th>
            </tr>
        </thead>
        <tbody>
        {% for event in events %}
            <tr>
                <td class="font-weight-bold">{{ event.artisteId.nom }}</td>
                <td>{{ event.type }}</td>
                <td>{{ event.dateStart ? event.dateStart|date('d-m-Y') : '' }}</td>
            
                <td>{{ event.lieu }}</td>
                <td>{{ event.ville }}</td>
               
               
                <td>
                    <a class= "btn btn-dark" href="{{ path('event_show', {'id': event.id}) }}">{% trans %}Voir la fiche de l'événement{% endtrans %}</a>
                   {% if is_granted('ROLE_SUPER_ADMIN') %}
                    <a class= "btn btn-secondary" href="{{ path('event_edit', {'id': event.id}) }}">{% trans %}Editer{% endtrans %}</a>
                {% endif %}
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="9">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% if is_granted('ROLE_SUPER_ADMIN') %}
    <a class= "btn btn-secondary" href="{{ path('event_new') }}">{% trans %}Créer un nouvel artiste{% endtrans %}</a>
    
     {% endif %}
{% endblock %}

templates/event/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Event{% endblock %}

{% block body %}
    <h1>Create new Event</h1>

    {{ include('event/_form.html.twig') }}

    <a href="{{ path('event_index') }}">back to list</a>
{% endblock %}

templates/event/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Event{% endblock %}

{% block body %}
<h1>Event</h1>

<table class="table">
    <tbody>
        <tr>
            <th>Artiste</th>
            <td>{{ event.artisteId.nom }}</td>
        </tr>
        <tr>
            <th>Type</th>
            <td>{{ event.type }}</td>
        </tr>
        <tr>
            <th>Date_start</th>
            <td>{{ event.dateStart ? event.dateStart|date('d-m-Y') : '' }}</td>
        </tr>
        <tr>
            <th>Date_end</th>
            <td>{{ event.dateEnd ? event.dateEnd|date('d-m-Y') : '' }}</td>
        </tr>
        <tr>
            <th>Lieu</th>
            <td>{{ event.lieu }}</td>
        </tr>
        <tr>
            <th>Ville</th>
            <td>{{ event.ville }}</td>
        </tr>
        <tr>
            <th>Description</th>
            <td>{{ event.description }}</td>
        </tr>
        <tr>
            <th>Prix</th>
            <td>{{ event.prix }}</td>
        </tr>
    </tbody>
</table>

<a class="btn btn-outline-dark" href="{{ path('event_index') }}">back to list</a>

{% if is_granted('ROLE_SUPER_ADMIN') %}
<a class="btn btn-primary" href="{{ path('event_edit', {'id': event.id}) }}">edit</a>
{% endif %}

{{ include('event/_delete_form.html.twig') }}



<p> Cordonnées de la ville : X = {{ ville[1] }} et Y = {{ ville[0] }}

    <div id="mapid" style="height:300px;width:800px"></div>

    <script>
        var mymap = L.map('mapid').setView([{{ ville[1] }}, {{ ville[0] }}], 25);
        L.tileLayer('https://api.tiles.mapbox.com/v4/{id}/{z}/{x}/{y}.png?access_token={accessToken}', {
            attribution: 'Map data &copy; <a href="https://www.openstreetmap.org/">OpenStreetMap</a> contributors, <a href="https://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>, Imagery © <a href="https://www.mapbox.com/">Mapbox</a>',
            maxZoom: 18,
            id: 'mapbox.streets',
            accessToken: 'pk.eyJ1Ijoib2xpZ3JhYWwiLCJhIjoiY2p6bGVnYjd1MDN6NjNtdDZ4cmc5OXQyMyJ9.YRJU--EMmYxn823YyMf3LQ'
        }).addTo(mymap);
    </script>
    {% endblock %}