src/Entity/Actualite.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ActualiteRepository")
 */
class Actualite
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $thematique;

    /**
     * @ORM\Column(type="text")
     */
    private $contenu;

    /**
     * @ORM\Column(type="date")
     */
    private $date_publication;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\User", inversedBy="actualites")
     */
    private $id_user;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Artiste", inversedBy="actualites")
     */
    private $id_artiste;

    public function __construct()
    {
        $this->id_user = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getThematique(): ?string
    {
        return $this->thematique;
    }

    public function setThematique(string $thematique): self
    {
        $this->thematique = $thematique;

        return $this;
    }

    public function getContenu(): ?string
    {
        return $this->contenu;
    }

    public function setContenu(string $contenu): self
    {
        $this->contenu = $contenu;

        return $this;
    }

    public function getDatePublication(): ?\DateTimeInterface
    {
        return $this->date_publication;
    }

    public function setDatePublication(\DateTimeInterface $date_publication): self
    {
        $this->date_publication = $date_publication;

        return $this;
    }

    /**
     * @return Collection|User[]
     */
    public function getIdUser(): Collection
    {
        return $this->id_user;
    }

    public function addIdUser(User $idUser): self
    {
        if (!$this->id_user->contains($idUser)) {
            $this->id_user[] = $idUser;
        }

        return $this;
    }

    public function removeIdUser(User $idUser): self
    {
        if ($this->id_user->contains($idUser)) {
            $this->id_user->removeElement($idUser);
        }

        return $this;
    }

    public function getIdArtiste(): ?Artiste
    {
        return $this->id_artiste;
    }

    public function setIdArtiste(?Artiste $id_artiste): self
    {
        $this->id_artiste = $id_artiste;

        return $this;
    }
    
}

src/Form/ActualiteType.php
<?php

namespace App\Form;

use App\Entity\Actualite;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ActualiteType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('thematique')
            ->add('contenu')
            ->add('date_publication')
           // ->add('id_user')
            ->add('id_artiste')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Actualite::class,
        ]);
    }
}

src/Controller/ActualiteController.php
<?php

namespace App\Controller;

use App\Entity\Actualite;
use App\Form\ActualiteType;
use App\Repository\ActualiteRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/actualite")
 */
class ActualiteController extends AbstractController
{
    /**
     * @Route("/", name="actualite_index", methods={"GET"})
     */
    public function index(ActualiteRepository $actualiteRepository): Response
    {
        return $this->render('actualite/index.html.twig', [
            'actualites' => $actualiteRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="actualite_new", methods={"GET","POST"})
     */
    public function new(Request $request, Actualite $actualite): Response
    {   
        $this->denyAccessUnlessGranted('createActu', $actualite);
        
        $form = $this->createForm(ActualiteType::class, $actualite);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($actualite);
            $entityManager->flush();

            return $this->redirectToRoute('actualite_index');
        }

        return $this->render('actualite/new.html.twig', [
            'actualite' => $actualite,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="actualite_show", methods={"GET"})
     */
    public function show(Actualite $actualite): Response
    {
    
        return $this->render('actualite/show.html.twig', [
            'actualite' => $actualite,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="actualite_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Actualite $actualite): Response
    {
        $this->denyAccessUnlessGranted('editActu', $actualite);
        $form = $this->createForm(ActualiteType::class, $actualite);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('actualite_index');
        }

        return $this->render('actualite/edit.html.twig', [
            'actualite' => $actualite,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="actualite_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Actualite $actualite): Response
    {
        $this->denyAccessUnlessGranted('deleteActu', $actualite);
        if ($this->isCsrfTokenValid('delete'.$actualite->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($actualite);
            $entityManager->flush();
        }

        return $this->redirectToRoute('actualite_index');
    }
}

templates/actualite/_delete_form.html.twig
<form method="post" action="{{ path('actualite_delete', {'id': actualite.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ actualite.id) }}">
    <button class="btn">Delete</button>
</form>

templates/actualite/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form, {'attr':{'class':'form'}}) }}
    <div class="my-custom-class-for-errors">
    {{ form_errors(form) }}
</div>

<div class="row">
    <div class="form-group col-md-5">
        {{ form_row(form.id_artiste) }}
    </div>
    <div class="form-group col-md-10">
        {{ form_row(form.thematique) }}
    </div>
    <div class="form-group col-md-6">
        {{ form_row(form.date_publication) }}
    </div>
    
    <div class="form-group col-md-5">
        {{ form_row(form.contenu) }}
    </div>
    

    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/actualite/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Actualite{% endblock %}

{% block body %}
    <h1>Edit Actualite</h1>

    {{ include('actualite/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('actualite_index') }}">back to list</a>

    {{ include('actualite/_delete_form.html.twig') }}
{% endblock %}

templates/actualite/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Actualite index{% endblock %}

{% block body %}
    <h2>{% trans %}Actualite{% endtrans %}</h2>
{% for message in app.flashes('success') %}
            <div class="alert alert-success">
                {{ message }}
            </div>
        {% endfor %}
    <table class="table table-bordered table-hover">
        <thead class="thead-dark">
            <tr>
                <th>Artiste</th>
                <th>Thematique</th>
                <th>Contenu</th>
                <th>Date_publication</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for actualite in actualites %}
            <tr>
                <td class="font-weight-bold">{{ actualite.idArtiste.nom }}</td>
                <td>{{ actualite.thematique }}</td>
                <td>{{ actualite.contenu }}</td>
                <td>{{ actualite.datePublication ? actualite.datePublication|date('d-m-Y') : '' }}</td>
                <td>
                    <a href="{{ path('actualite_show', {'id': actualite.id}) }}">Voir l'actualité</a>
                 {% if is_granted('ROLE_SUPER_ADMIN') %}
                    <a href="{{ path('actualite_edit', {'id': actualite.id}) }}">edit</a>
              {% endif %}
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="5">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
 {% if is_granted('ROLE_SUPER_ADMIN') %}
    <a href="{{ path('actualite_new') }}">Create new</a>
     {% endif %}
{% endblock %}

templates/actualite/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Actualite{% endblock %}

{% block body %}
    <h1>Create new Actualite</h1>

    {{ include('actualite/_form.html.twig') }}

    <a href="{{ path('actualite_index') }}">back to list</a>
{% endblock %}

templates/actualite/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Actualite{% endblock %}

{% block body %}
    <h1>Actualite</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ actualite.id }}</td>
            </tr>
            <tr>
                <th>Thematique</th>
                <td>{{ actualite.thematique }}</td>
            </tr>
            <tr>
                <th>Contenu</th>
                <td>{{ actualite.contenu }}</td>
            </tr>
            <tr>
                <th>Date_publication</th>
                <td>{{ actualite.datePublication ? actualite.datePublication|date('Y-m-d') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('actualite_index') }}">back to list</a>

    <a href="{{ path('actualite_edit', {'id': actualite.id}) }}">edit</a>

    {{ include('actualite/_delete_form.html.twig') }}
{% endblock %}